version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contract-extractor-backend
    environment:
      - FLASK_ENV=development
      - PORT=5000
      # Set your key in the environment when running: MISTRAL_API_KEY=sk_... docker compose up
      - MISTRAL_API_KEY
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: contract-extractor-frontend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
